language: node_js
node_js: '8'
script:
  - |
    val=$(node checkFormat.js);
    if [[ $val != 0 ]]; then
      echo "Formatting errors! Please check your object keys spellings, commas and or other things that might invalidate your JSON and try again";
      exit 1;
    else
      echo "No errors";
      exit 0;
    fi
